# Generated by Django 4.2.3 on 2023-07-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='writer_id',
            new_name='id',
        ),
    ]
